### ISSUE TITLE
Question: Which encoding does the parser consider?

### ISSUE THREAD

**Issue by HeikoStudt** [mixerp/MixERP.Net.VCards#1]
Hi,

I am quite new to VCards, so probably I got it all wrong...
I scimmed the code but did not see any encoding consideration.

In VCard (2.1?) there is this notion of inline-encoding like "FN;CHARSET=UTF-8:üüü".
Do you support that style?

According to https://android.stackexchange.com/questions/106888/what-vcard-formats-versions-and-encodings-are-supported-for-import, the versions are different in their regard of default encodings.
Though, the information collides a bit against https://de.wikipedia.org/wiki/VCard.

As this project seems to be live, I am considering it for parsing/changing the vcard address book of Becky! Internet Mail from outside. However, I would like to be as international as Becky! is having both Japanese and Western European users, and I am stuck with Becky! libraries' ableness for VCards.
In manual tests I got Becky read in the UTF-8 inline correctly (for FN) while Becky is using ISO or win 1252 per default for new entries. As said, I need to support both.

Luckily, currently I only want to add new VCard entries into the file and parse the email out of it, so a no-framework-approach would work as well. But, of course, I need to read quite deeply about folding and such.

MFG

**Comment by mixerp** [comment]
Hello,

> In VCard (2.1?) there is this notion of inline-encoding like "FN;CHARSET=UTF-8:üüü".

I'm afraid that's not supported.

When producing vCards, we encode them using UTF-8. Whereas, while opening a file, the encoding is not assumed or expected to be UTF-8:

https://github.com/mixerp/MixERP.Net.VCards/blob/master/src/MixERP.Net.VCards/Helpers/FileHelper.cs#L16-L29

> Luckily, currently I only want to add new VCard entries into the file and parse the email out of it, so a no-framework-approach would work as well. But, of course, I need to read quite deeply about folding and such.

MixERP.Net.VCards creates valid vCard(s) in any version (2.1+). Plus, the parser is extremely forgiving and tolerant to a malformed vCard(s). I hope this helped. Keep posting!!!

**Comment by HeikoStudt** [comment]
Thanks for your comments.
According to the author of Becky! it reads Version 3.0 vCards as utf-8 anyway, so probably I will give it a try.
For the moment I've implemented the quick&dirty approach of regexing emails out and appending malformed vcard lines. ;-)

MFG
