### ISSUE TITLE
Folded fields don't work

### ISSUE THREAD

**Issue by exyi** [mixerp/MixERP.Net.VCards#16]
Field with values folded on multiple lines are not parsed correctly (see Folded in https://tools.ietf.org/html/rfc6350)

For example, when I have a long field `NOTE`, it is folded on multiple lines to avoid lines longer than 75 chars:

```
NOTE:Lorem ipsum dolor sit amet\, consectetur adipiscing elit\, sed do eius
 mod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim v
 eniam\, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea co
 mmodo consequat.
```

But it is not loaded correctly.

I have fixed that in my fork https://github.com/exyi/MixERP.Net.VCards/, so you can take it. I'm not sending a PR, since I have made few more changes to make it build in my project and I don't want to pollute your repo with that.

**Comment by binodnp** [comment]
Thank you exyi.
