### ISSUE TITLE
Error: An item with the same key has already been added. Key: TYPE

### ISSUE THREAD

**Issue by dgwaldo** [mixerp/MixERP.Net.VCards#6]
Loaded the library tonight to parse a .vcf file.  Tried multiple files, and this is the error I received.

An item with the same key has already been added. Key: TYPE

Here is the code generating the error. The .vcard file download is from google contacts.

	```
	public IEnumerable<Contact> GetContacts(Stream stream) {
			var reader = new StreamReader(stream, encoding: Encoding.UTF8);
			string contents = reader.ReadToEnd();
			IEnumerable<VCard> vCards = MixERP.Net.VCards.Deserializer.GetVCards(contents);

			var contacts = new List<Contact>();
			foreach (var vcard in vCards) {
				contacts.Add(MapVCardToContact(vcard));
			}
			return contacts;
		}

		private Contact MapVCardToContact(VCard card) {
			var contact = new Contact {
				FirstName = card.FirstName,
				LastName = card.LastName,
				Company = card.Organization,
				JobTitle = card.Title,
				Note = card.Note
			};

			foreach (var f in card.Telephones) {
				contact.PhoneNumbers.Add(new PhoneNumber {
					DialNumber = f.Number,
					Label = f.Type.ToString()
				});
			}

			foreach (var e in card.Emails) {
				contact.EmailAddresses.Add(new EmailAddress {
					Email = e.EmailAddress,
					Label = e.Type.ToString()
				});
			}

			foreach (var a in card.Addresses) {
				contact.Addresses.Add(new Address {
					PostalCode = a.PostalCode,
					City = a.Locality,
					Region = a.Region,
					Street1 = a.Street,
					Street2 = a.PoBox,
					Label = a.Type.ToString()
				});
			}

			return contact;
		}
```

I loaded up the library in the debugger. It looks like the regex helper to split cards is the actual issue, looks like maybe an issue with the input data stream.

**Comment by dgwaldo** [comment]
Hmm, so working on this is small chunks has been a little confounding. It does appear that the complete fix for me was modifying the Regex and cleaning the array of empty items. That along with the guard if on the the parser inserting into the dictionary seemed to do the trick.

`	var reader = new StreamReader(stream, encoding: Encoding.UTF8);
			string contents = reader.ReadToEnd();

			var vCardArray = Regex.Split(contents, @"(BEGIN:VCARD.*?END:VCARD)", RegexOptions.Singleline);
			List<string> cleanedCards = new List<string>();
			foreach (var text in vCardArray) {
				if (!String.IsNullOrWhiteSpace(text)) {
					cleanedCards.Add(text);
				}
			}
			var vCards = cleanedCards.Select(x => Deserializer.GetVCard(x));`

**Comment by zweihan** [comment]
Hi, I am facing the same issue. I realised that some fields have multiple TYPE values. For example,
`EMAIL;TYPE=INTERNET;TYPE=PREF;TYPE=WORK:email@company.com`
This would cause the parser to break with the above mentioned error.

**Comment by dgwaldo** [comment]
Looks like this should be closed as the PR was merged.

**Comment by mayankjain34** [comment]
Hi,

Can you please publish these changes the last release was on February 20, 2017.

Thanks,
Mayank
